/* AUTO-GENERATED by scripts/sync-brand.mjs — edit brand/brand.config.json */
export const brand = {
  "productName": "Red Requester",
  "identifier": "io.reddb.requester",
  "tagline": "Open-source API client, powered by recker.",
  "accentColor": "#ff2056",
  "repoUrl": "https://github.com/reddb-io/red-requester",
  "supportUrl": "https://github.com/reddb-io/red-requester/issues",
  "deepLinkScheme": "redrequester"
} as const;
