/* AUTO-GENERATED by scripts/sync-brand.mjs — edit brand/brand.config.json */
export const brand = {
  "productName": "Red Request",
  "binaryName": "red-request",
  "monogram": "R",
  "identifier": "io.reddb.request",
  "tagline": "Open-source API client, powered by recker.",
  "accentColor": "#ff2056",
  "repoUrl": "https://github.com/reddb-io/red-request",
  "supportUrl": "https://github.com/reddb-io/red-request/issues",
  "deepLinkScheme": "redrequest"
} as const;
