version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      js-dependencies:
        patterns: ["*"]

  - package-ecosystem: cargo
    directory: "/apps/desktop/src-tauri"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      rust-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
