#!/usr/bin/env node
// Stamp the single brand config (brand/brand.config.json) into every place that needs
// branding: the Tauri config, the UI theme tokens, and the runtime brand constants.
// Rebranding = edit brand.config.json + swap the logo + run `pnpm brand:sync`.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(resolve(root, p), "utf8");
const brand = JSON.parse(read("brand/brand.config.json"));

const GEN =
  "/* AUTO-GENERATED by scripts/sync-brand.mjs — edit brand/brand.config.json */";

function syncTauriConf() {
  const p = "apps/desktop/src-tauri/tauri.conf.json";
  if (!existsSync(resolve(root, p))) return skip(p);
  const conf = JSON.parse(read(p));
  conf.productName = brand.productName;
  conf.identifier = brand.identifier;
  conf.app ??= {};
  conf.app.windows ??= [{}];
  conf.app.windows[0].title = brand.productName;
  conf.bundle ??= {};
  conf.bundle.shortDescription = brand.tagline ?? brand.productName;
  conf.plugins ??= {};
  conf.plugins["deep-link"] = {
    desktop: { schemes: [brand.deepLinkScheme] },
  };
  writeFileSync(resolve(root, p), JSON.stringify(conf, null, 2) + "\n");
  done(p);
}

function syncThemeCss() {
  const p = "packages/ui/src/lib/brand.generated.css";
  const tokens = Object.entries(brand.bgTokens)
    .map(([k, v]) => `  --color-${k}: ${v};`)
    .join("\n");
  // Emitted as --color-brand (NOT --color-accent): shadcn-svelte owns the `accent`
  // token namespace (subtle hover bg); our brand red flows through shadcn's `primary`.
  const css = `${GEN}\n@theme {\n  --color-brand: ${brand.accentColor};\n${tokens}\n}\n`;
  writeFileSync(resolve(root, p), css);
  done(p);
}

function syncBrandTs() {
  const p = "packages/ui/src/lib/brand.generated.ts";
  const ts =
    `${GEN}\n` +
    `export const brand = ${JSON.stringify(
      {
        productName: brand.productName,
        // Lowercase technical name (e.g. "red-request") — used where it pairs with
        // other lowercase tokens like the engine/reddb name. Falls back to a slug.
        binaryName:
          brand.binaryName ||
          brand.productName.toLowerCase().replace(/\s+/g, "-"),
        // Accent badge mark: explicit `monogram`, else the productName's initial.
        monogram: (brand.monogram || brand.productName[0] || "").toUpperCase(),
        identifier: brand.identifier,
        tagline: brand.tagline ?? "",
        accentColor: brand.accentColor,
        repoUrl: brand.repoUrl ?? "",
        supportUrl: brand.supportUrl ?? "",
        deepLinkScheme: brand.deepLinkScheme,
      },
      null,
      2
    )} as const;\n`;
  writeFileSync(resolve(root, p), ts);
  done(p);
}

const skip = (p) => console.log(`  skip   ${p} (not scaffolded yet)`);
const done = (p) => console.log(`  stamp  ${p}`);

console.log(`brand:sync → "${brand.productName}" (${brand.identifier})`);
syncTauriConf();
syncThemeCss();
syncBrandTs();
console.log("brand:sync done.");
